package src

import "fmt"

// GenerateRcdScript writes a classic BSD-style /etc/rc.d/rc.<pkg>
// start/stop/restart script inside the container, for "system"-type
// packages landing on a distro whose image has no systemd at all (see
// Distro.InitSystem — Slackware, notably). Assuming a systemd unit exists
// there and pointing people at `systemctl` would just be wrong; this gives
// them the equivalent Slackware-native mechanism instead.
//
// This is deliberately simple (start = launch in background, stop = pkill
// by name) rather than a full LSB-style init script with PID files and
// status checks — real Slackware packages typically ship a proper rc.d
// script of their own as part of the package; this generated one is a
// reasonable generic fallback for packages that don't, not a replacement
// for one that does.
func GenerateRcdScript(cont, pkg string) error {
	script := fmt.Sprintf(`#!/bin/sh
# /etc/rc.d/rc.%s — start/stop/restart the %s service.
# Generated by Isolator (this distro's image has no systemd — see
# Distro.InitSystem in distros.go — so "system"-type packages get a
# classic BSD-style rc.d script here instead of a unit file).

case "$1" in
  start)
    echo "Starting %s..."
    %s >/var/log/%s.log 2>&1 &
    echo $! > /var/run/%s.pid
    ;;
  stop)
    echo "Stopping %s..."
    if [ -f /var/run/%s.pid ]; then
      kill "$(cat /var/run/%s.pid)" 2>/dev/null
      rm -f /var/run/%s.pid
    else
      pkill -f "%s" 2>/dev/null
    fi
    ;;
  restart)
    "$0" stop
    sleep 1
    "$0" start
    ;;
  status)
    if [ -f /var/run/%s.pid ] && kill -0 "$(cat /var/run/%s.pid)" 2>/dev/null; then
      echo "%s is running (pid $(cat /var/run/%s.pid))"
    else
      echo "%s is not running"
    fi
    ;;
  *)
    echo "usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac
`, pkg, pkg, pkg, pkg, pkg, pkg, pkg, pkg, pkg, pkg, pkg, pkg, pkg, pkg, pkg, pkg)

	dest := "/etc/rc.d/rc." + pkg
	// Write via a heredoc through sh -c so we don't need a separate
	// podman-cp round trip for a few hundred bytes of shell script.
	writeCmd := fmt.Sprintf("cat > %s << 'ISOLATOR_RCD_EOF'\n%s\nISOLATOR_RCD_EOF\nchmod 755 %s", dest, script, dest)
	if !ExecInContainer(cont, writeCmd, false, true) {
		return fmt.Errorf("failed to write %s inside container '%s'", dest, cont)
	}

	// Wire it into rc.local so it actually starts on boot, the standard
	// Slackware way of adding a "local" service — idempotent (won't add
	// the line twice on reinstall).
	hookLine := fmt.Sprintf("[ -x %s ] && %s start", dest, dest)
	ensureCmd := fmt.Sprintf(
		"touch /etc/rc.d/rc.local && grep -qxF '%s' /etc/rc.d/rc.local || echo '%s' >> /etc/rc.d/rc.local",
		hookLine, hookLine)
	if !ExecInContainer(cont, ensureCmd, false, true) {
		PrintWarn("Wrote rc.d script but failed to hook it into rc.local — start it manually")
	}

	return nil
}

// RemoveRcdScript deletes the generated script and its rc.local hook line
// (best-effort — used by HandleRemove when removing a "system" package
// from a non-systemd distro).
func RemoveRcdScript(cont, pkg string) {
	dest := "/etc/rc.d/rc." + pkg
	ExecInContainer(cont, dest+" stop 2>/dev/null; rm -f "+dest, false, true)
	hookLine := fmt.Sprintf("[ -x %s ] && %s start", dest, dest)
	cleanupCmd := fmt.Sprintf("sed -i '\\#%s#d' /etc/rc.d/rc.local 2>/dev/null", hookLine)
	ExecInContainer(cont, cleanupCmd, false, true)
}
